services:
  - type: web
    name: websocket-chatbot-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: CLIENT_URL
        sync: false
